version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'eslint'
        versions: ['>=10']
      - dependency-name: '@eslint/js'
        versions: ['>=10']
    commit-message:
      prefix: '⬆️'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: '⬆️'
